# Dependencies
# Dependencies

highlighter:      rouge

# Permalinks
permalink:        pretty
theme: minima
remote_theme: adobe/hyde-theme


# Setup
title:            Trail Blazed
tagline:          'A path for aspiring Data Engineers'
description:      'This website will walk you through the roadmap of Cloud Data Engineer.'
url:              https://trailblazed.github.io/
baseurl:          "https://trailblazed.github.io/"

author:
  name:           'Tadepalli Sarada Kiranmayee'
  url:            https://www.linkedin.com/in/tadepalli-sarada-kiranmayee-082aba57/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:          https://github.com/TrailBlazed
