# Dependencies
# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Trail Blazed
tagline:          'A path for aspiring Data Engineers'
description:      'This website will walk you through the roadmap of Cloud Data Engineer.'
url:              https://trailblazed.github.io/
baseurl:          "https://trailblazed.github.io/"

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:          https://github.com/TrailBlazed
